language: java
dist: trusty
jdk: oraclejdk8
notifications:
  slack:
    secure: Yk5uHwIdTbaV+H0BchEsyZ6+TYHwD2aOCe1M5qU1kBjJI4pyR4huh3bMxIXyTVDSHdYcZ+Vk0P3KHUO0qQSnelifZGzGFIUp98Qh6ujl0AoqjzeLjK3hIiOgYxkT/R6zEVFR7Bn2xFmU3xYBPGtxn2OX7zq7B5FLVjXCpJaFLwPUepr9Ykn03UNfPwVm9oq9UEI8sDvEg7cjqPGbAERejm3lu0qk8AvPZ/Ajiw0lAiMYfy9sWm2PI9TIb0apQGzyJLFPZbPNfG1agOmHAYTJnDvi2KrFfZEweFrtXzmzSRxGwUGOF8QlTTTCTR2jXRKnuiJW0FsuT5rKnGrliR/56cufALuBouKPfSg6UNXxyi+Xy/qyF7nl14Z+PinUo+GXZp08ws6rWW4H5TEf2rWUelv3aUMQ3e9nRWNL3rhSMadFsuNerxLfQ3t8QV4JBcOxMStu7NgT6mHTjaNHAUS78UBq9StC9UAjxHRHAIvFSTATjDG1v47PaTnEnLBB4vhtsXPwDNHL8RqPII9Ldt07Fpw3ccj3we/JlzQ4H4z9+YN/oIQTTZweS7Z6kMrsq/gJFKBSimFIpR/9gMplMrBIYcBK4iqisNNYenBQNCpDrKEJgVy2XDSijaXFu4VtJHfjadgia+uZVHX5I7iHeZW16367cb82xPyu6csSCh64oe0=
cache:
  directories:
  - .autoconf
  - $HOME/.m2
script: mvn clean install